[package]
name = "tide-server-daemon"
version = "0.1.0"
authors = ["mygnu <tech@hgill.io>"]
edition = "2018"

[dependencies]
tide = "0.0.1"
config = "0.9.2"
serde = "1.0"
serde_derive = "1.0"

[profile.release]
lto = true
opt-level = 3